### ISSUE TITLE
S5 add timer 

### ISSUE THREAD

**Issue by lakicv** [sopra-fs21-group-17/pictures-client#33]
#11
#13 
#14 
#15 
#16 

**time estimate:** 0.5 days
description: add a maximum building time of 5 minutes which automatically submits all the boards once the timer is over.
the timer is displayed to all players.

**Comment by dkajin** [comment]
2898b43e3dce6b88325dbf552aeb04691f843671
a80064180485ec3bb8845e82565715a3194bfa3e
