### ISSUE TITLE
Optimize Lobby Frontend

### ISSUE THREAD

**Issue by lakicv** [sopra-fs21-group-17/pictures-client#61]
**time estimate:** 1.5 days

description: make lobby-code visible on screen, make count-down longer and bigger, make UI more beautifull.

**Comment by dkajin** [comment]
9aa7684822c2254c68e66045da983d5e8520fcd6
688a98a75cff639b250f107670155d275075fb06
4b59b5d038b5215cd6644b72366767757b55c400
35a5a8a9e5b232d68c41837498878a0adc524a04
23b2eb3f9ef48cec11a44dac8ab0bb36b214f232
